export const accounts = [
  {
    id: "brokerage",
    name: "Brokerage Account",
    number: "72981482*",
    type: "Self-managed",
    balance: 453019.15,
    canSell: true,
  },
  {
    id: "cash-plus",
    name: "Cash Plus Account",
    number: "72981482**",
    type: "Self-managed",
    balance: 30011.01,
    canSell: false,
  },
  {
    id: "trad-ira",
    name: "Traditional IRA Brokerage Account",
    number: "72981482*",
    type: "Self-managed",
    balance: 21665.38,
    canSell: true,
  },
  {
    id: "roth-ira",
    name: "Roth IRA Brokerage Account",
    number: "72981482*",
    type: "Self-managed",
    balance: 68894.48,
    canSell: true,
  },
  {
    id: "529",
    name: "Individual 529 College Savings Account",
    number: "72981482*",
    type: "Self-managed",
    balance: 17775.71,
    canSell: true,
  },
];

export const totalBalance = accounts.reduce((sum, a) => sum + a.balance, 0);

export const brokerageFunds = [
  {
    id: "vtsax",
    name: "Total Stock Mkt Index",
    ticker: "VTSAX",
    shareClass: "Admiral",
    method: "MinTax",
    totalValue: 312400,
    stGainLoss: 35.30,
    ltGainLoss: 68210,
    totalGainLoss: 68245,
    recommendedSell: 6000,
    stGainOnSell: 21,
    ltGainOnSell: 5226,
    estTax: 784,
    rebalancing: { before: 4.9, after: 3.7, target: 3.2, label: "US Equity" },
    rationale: "Over-allocated; LT lots used",
    lots: [
      { date: "12/22/2025", qty: 0.164, costShare: 633.96, totalCost: 103.97, mktValue: 103.73, stGL: -0.24, ltGL: null, gainPct: -0.23, term: "ST 307d" },
      { date: "09/29/2025", qty: 0.166, costShare: 613.49, totalCost: 101.84, mktValue: 105.00, stGL: 3.16, ltGL: null, gainPct: 3.10, term: "ST 223d" },
      { date: "06/28/2024", qty: 0.261, costShare: 504.44, totalCost: 131.66, mktValue: 165.09, stGL: null, ltGL: 33.43, gainPct: 25.39, term: "LT" },
    ],
  },
  {
    id: "vfiax",
    name: "500 Index Fund",
    ticker: "VFIAX",
    shareClass: "Admiral",
    method: "MinTax",
    totalValue: 218600,
    stGainLoss: 38.46,
    ltGainLoss: 26107,
    totalGainLoss: 26146,
    recommendedSell: 0,
    stGainOnSell: null,
    ltGainOnSell: null,
    estTax: null,
    rebalancing: null,
    rationale: "ST lots pending LT conversion",
    waitDays: 45,
    waitSavings: 218,
    lots: [],
  },
  {
    id: "vbtlx",
    name: "Total Bond Mkt",
    ticker: "VBTLX",
    shareClass: "Admiral",
    method: "FIFO",
    totalValue: 92893,
    stGainLoss: null,
    ltGainLoss: -4210,
    totalGainLoss: -4210,
    recommendedSell: 4000,
    stGainOnSell: null,
    ltGainOnSell: -1820,
    estTax: -273,
    rebalancing: { before: 20.5, after: 20.3, target: 20.0, label: "Fixed Income" },
    rationale: "Harvests LT loss; offsets gains",
    lots: [],
  },
];

export const iraFunds = [
  {
    id: "vtiax",
    name: "Total Intl Stock Index",
    ticker: "VTIAX",
    shareClass: "Admiral",
    method: "N/A",
    totalValue: 142800,
  },
  {
    id: "vbtlx-ira",
    name: "Total Bond Market",
    ticker: "VBTLX",
    shareClass: "Admiral",
    method: "N/A",
    totalValue: 80600,
  },
];

export const autoSummary = {
  saleAmount: 10000,
  estimatedTax: 511,
  effectiveTaxRate: 5.11,
  rebalancingImpact: "Improved",
  usDriftBefore: 4.9,
  usDriftAfter: 3.2,
};

export const manualSummary = {
  totalSale: 10000,
  stCapitalGains: 31,
  ltCapitalGains: 7839,
  lossesHarvested: -421,
  estTotalTax: 1114,
  effectiveTaxRate: 11.14,
};
